spring:
  application:
    name: 711

  datasource:
    url: jdbc:postgresql://turntable.proxy.rlwy.net:42746/railway
    username: postgres
    password: NmOKvvmDHREiRCbHUKYBVzTAJLeibTHP
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: j4G$z8LpN9vJ^T3Qb7fE2k!wYcB1uL0zRxH5MvAhDpXsCgKj
  expiration: 86400000
  refreshExpiration: 604800000

vnpay:
  tmnCode: H9SLU363
  hashSecret: MH2TNFTKVRUU0O4I5VD373QI06D346B7
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#  returnUrl: https://furnimart.click/api/v1/payment/vnpay-return
  returnUrl: https://711-fe.vercel.app/api/payment/vnpay-return

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method